### ISSUE TITLE
Error: Cannot find module 'daisyui/dist/unstyled.rtl.js'

### ISSUE THREAD

**Issue by B1ackg0d** [kidonng/unocss-preset-daisy#37]
pnpm dev:open

> tov-template@1.18.0 dev:open D:\Project\tov-template-main
> vite --open

node:internal/modules/cjs/loader:1090
  const err = new Error(message);
              ^

Error: Cannot find module 'daisyui/dist/unstyled.rtl.js'
Require stack:
- D:\Project\tov-template-main\node_modules\.pnpm\unocss-preset-daisy@7.0.0_daisyui@4.4.4_unocss@0.57.7\node_modules\unocss-preset-daisy\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1090:15)
    at Function.resolve (node:internal/modules/helpers:125:19)
    at _resolve (D:\Project\tov-template-main\node_modules\.pnpm\jiti@1.21.0\node_modules\jiti\dist\jiti.js:1:251148)
    at jiti (D:\Project\tov-template-main\node_modules\.pnpm\jiti@1.21.0\node_modules\jiti\dist\jiti.js:1:253746)
    at D:/Project/tov-template-main/node_modules/.pnpm/unocss-preset-daisy@7.0.0_daisyui@4.4.4_unocss@0.57.7/node_modules/unocss-preset-daisy/index.js:10:43
    at evalModule (D:\Project\tov-template-main\node_modules\.pnpm\jiti@1.21.0\node_modules\jiti\dist\jiti.js:1:256443)
    at jiti (D:\Project\tov-template-main\node_modules\.pnpm\jiti@1.21.0\node_modules\jiti\dist\jiti.js:1:254371)
    at D:/Project/tov-template-main/uno.config.ts:12:26
    at evalModule (D:\Project\tov-template-main\node_modules\.pnpm\jiti@1.21.0\node_modules\jiti\dist\jiti.js:1:256443)
    at jiti (D:\Project\tov-template-main\node_modules\.pnpm\jiti@1.21.0\node_modules\jiti\dist\jiti.js:1:254371)
    at loadConfigFile (file:///D:/Project/tov-template-main/node_modules/.pnpm/unconfig@0.3.11/node_modules/unconfig/dist/index.mjs:153:13)
    at async Object.load (file:///D:/Project/tov-template-main/node_modules/.pnpm/unconfig@0.3.11/node_modules/unconfig/dist/index.mjs:76:24)
    at async loadConfig (file:///D:/Project/tov-template-main/node_modules/.pnpm/@unocss+config@0.57.7/node_modules/@unocss/config/dist/index.mjs:43:18)
    at async reloadConfig (file:///D:/Project/tov-template-main/node_modules/.pnpm/@unocss+vite@0.57.7_vite@4.4.11/node_modules/@unocss/vite/dist/index.mjs:89:20) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\Project\\tov-template-main\\node_modules\\.pnpm\\unocss-preset-daisy@7.0.0_daisyui@4.4.4_unocss@0.57.7\\node_modules\\unocss-preset-daisy\\index.js'
  ]
}

Node.js v19.6.1
 ELIFECYCLE  Command failed with exit code 1.

 
 
 Hello,
 I'm trying to preset daisyui in Vue3+Ts, but this error occurred. I'm using pnpm for the build. Can you provide me with some ideas to solve this problem? Thank you very much.

**Comment by russelgal** [comment]
`"daisyui": "3.9.4"`
and it will be all right

**Comment by yicone** [comment]
@russelgal is right, I'm using a similar approach
`npm install daisyui@^3.9.4`

**Comment by yicone** [comment]
Duplicate of #35

**Comment by whoooami** [comment]
It still not work with node v21.0, daisy: 4.6.2
`
  (node:31653) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
error when starting dev server:
Error: Cannot find module 'daisyui/dist/unstyled.rtl.js'
Require stack:
- node_modules/.pnpm/unocss-preset-daisy@7.0.0_daisyui@4.6.2_unocss@0.58.1/node_modules/unocss-preset-daisy/index.js
`

**Comment by hezhongfeng** [comment]
same.
